# Site wide configuration

title: Preston Parry
description: "a software engineer's blog about web development, data science, learning javascript, climbing, biking, bouldering, and cycling"
logo: HalfStache120x120.jpg
teaser: BikeSeatFlower375x250.jpg
locale: en_US
baseurl: /
url: //ClimbsRocks.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Preston Parry
  web: http://www.prestonparry.com
  email: 
  twitter: 
  bio: "climbs, bikes, and codes"
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
